name: Build & Publish
on:
  workflow_run:
    workflows: 
    - "Bump Semantic Version"
    types:
    - completed 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Get Current tag'
      id: currenttag
      uses: "WyriHaximus/github-action-get-previous-tag@v1.22"
      with:
        fallback: 0.1.0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup NuGet
      run: dotnet nuget add source --username DotNet-Ninja --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DotNet-Ninja/index.json"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:ContinuousIntegrationBuild=true /p:version=${{ steps.currenttag.outputs.tag }}

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Package Artifacts
      run: dotnet pack --configuration Release --no-build --output _packages /p:version=${{ steps.currenttag.outputs.tag }}

    - name: List Packages
      run: ls -la _packages/*nupkg

    - name: Publish NuGet and symbols
      id: nuget-push
      run: dotnet nuget push _packages/*nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create-release
      uses: DotNet-Ninja/Create-Release@main
      with:
        version: ${{ steps.currenttag.outputs.tag }}
        tag: ${{ steps.currenttag.outputs.tag }}
        description: "Release v{0}"
        owner: ${{ github.repository_owner }}
        name: DotNetNinja.Web
        accesstoken: ${{ secrets.GITHUB_TOKEN }}
