name: Pull Request - Validate Semantic Version
on:
  pull_request:
    branches: 
    - "main"

jobs:
  bump-tag-version:
    name: Validate Semantic Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: jefflinse/pr-semver-bump@v1.3.3
        name: Validate
        with:
          mode: validate
          repo-token:  ${{ secrets.GITHUB_TOKEN }} 
          major-label: major
          minor-label: minor
          patch-label: patch
          require-release-notes: true
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: false